---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# R-package `sparsegl`

The goal of sparsegl is to fit regularization paths for sparse group-lasso
penalized learning problems. The model is fit for a sequence of the regularization
parameter lambda.

## Installation

You can install the released version of sparsegl from [CRAN](https://CRAN.R-project.org) with:

```{r, echo = TRUE, eval = FALSE}
install.packages("sparsegl")
```

And the development version from [GitHub](https://github.com/) with:

```{r, echo = TRUE, eval = FALSE}
# install.packages("remotes")
remotes::install_github("dajmcdon/sparsegl")
```

## Minimal Example

```{r load-library, echo = FALSE}
library(sparsegl)
```

```{r minimal-ex, echo = TRUE, fig.align = 'center'}
set.seed(1010)
n <- 100
p <- 200
X <- matrix(data = rnorm(n*p, mean = 0, sd = 1), nrow = n, ncol = p)
eps <- rnorm(n, mean = 0, sd = 1)
beta_star <- c(rep(5, 5), c(5, -5, 2, 0, 0), rep(-5, 5), c(2, -3, 8, 0, 0), rep(0, (p - 20)))
y <- X %*% beta_star + eps
groups <- rep(1:(p / 5), each = 5)
plot(fit1, grouped = TRUE, y_axis = "coef", x_axis = "norm")
```

