---
title: "Script_for_plotting"
output: html_document
---

```{r setup, include = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(SGL)
library(gglasso)
library(sparsegl)

library(dplyr)
library(tidyr)
library(ggplot2)

library(microbenchmark)
```


```{r, functions, eval = FALSE}

beta_generate <- function(p, within_group = TRUE, group_size) {
  if (!within_group) {
    beta_star <- c(rep(5, 5), rep(-5, 5), c(2, -3, 8, 1, 3), c(5, -5, 2, -2, 1),
                   rep(c(-5, 0, 1, 5), each = 5, times = (p - 20) / 20))
  } else {
    beta_star <- c(rep(5, 5), c(5, -5, 2, 0, 0), rep(-5, 5), c(2, -3, 8, 0, 0),
                   rep(c(rep(5, 5), rep(0, 5), rep(-5, 5), c(2, 3, 5, 0, 0)), times = (p - 20) / 20))
  }
  beta_star
}


simulate <- function(change_list,
                     change_feature = c("n", "p"),
                     within_group = TRUE,
                     group_size = 5,
                     family = c("gaussian", "binomial")) {
  change_feature <- match.arg(change_feature)
  family <- match.arg(family, c("gaussian", "binomial"))
  df <- list()
  k <- 1

  if (change_feature == "n") {
    p <- 100
    beta_star <- beta_generate(p, within_group, group_size)
    groups <- rep(1:(p / group_size), each = group_size)
  } else {
    n <- 100
  }

  for (i in seq(length(change_list))) {
    if (change_feature == "n") {
      n <- change_list[i]
    } else {
      p <- change_list[i]
      beta_star <- beta_generate(p, within_group, group_size)
      groups <- rep(1:(p / group_size), each = group_size)
    }
    set.seed(101)
    X <- matrix(rnorm(n * p), nrow = n)
    for (j in seq(50)) {
      set.seed(j)
      if (family == "gaussian") {
        eps <- rnorm(n)
        y <- X %*% beta_star + eps
        data <- list(x = X, y = y)
        y_gglasso <- y
      } else {
        pr <- 1 / (1 + exp(-X %*% beta_star))
        y <- rbinom(n, 1, pr)
        data <- list(x = X, y = y)
        y_gglasso <- y
        y_gglasso[which(y_gglasso == 0)] <- -1
      }
      if (!within_group) {
        df[[k]] <- as.data.frame(summary(
          microbenchmark(sparsegl = sparsegl(X, y, groups, family = family, asparse = 0, standardize = FALSE),
                         SGL = SGL(data, groups, type = ifelse(family == "gaussian", "linear", "logit"), alpha = 0, nlam = 100, standardize = FALSE),
                         gglasso = gglasso(X, y_gglasso, groups, loss = ifelse(family == "gaussian", "ls", "logit")),
                         times = 1)))
      } else {
        df[[k]] <- as.data.frame(summary(
          microbenchmark(sparsegl = sparsegl(X, y, groups, family = family, asparse = 0.05, standardize = FALSE),
                         SGL = SGL(data, groups, type = ifelse(family == "gaussian", "linear", "logit"), alpha = 0.05, nlam = 100, standardize = FALSE),
                         times = 1)))
      }
      df[[k]] <- df[[k]] %>%
        select(expr, mean) %>%
        mutate(
          change_feature = factor(change_feature),
          change_list := factor(!!rlang::sym(change_feature)),
          within_group = within_group)
      k <- k + 1
      print(k)
    }
  }
  datf <- bind_rows(df)
  return(datf)
}

within_p <- simulate(change_list = c(20, 60, 100, 200, 300, 500), change_feature = "p", within_group = TRUE, group_size = 5, family = "gaussian")
within_n <- simulate(change_list = c(20, 60, 100, 200, 300, 500), change_feature = "n", within_group = TRUE, group_size = 5, family = "gaussian")
without_p <- simulate(change_list = c(20, 60, 100, 200, 300, 500), change_feature = "p", within_group = FALSE, group_size = 5, family = "gaussian")
without_n <- simulate(change_list = c(20, 60, 100, 200, 300, 500), change_feature = "n", within_group = FALSE, group_size = 5, family = "gaussian")



log_within_p <- simulate(change_list = c(20, 60, 100, 200, 300, 500), change_feature = "p", within_group = TRUE, group_size = 5, family = "binomial")
log_within_n <- simulate(change_list = c(20, 60, 100, 200, 300, 500), change_feature = "n", within_group = TRUE, group_size = 5, family = "binomial")
log_without_p <- simulate(change_list = c(20, 60, 100, 200, 300, 500), change_feature = "p", within_group = FALSE, group_size = 5, family = "binomial")
log_without_n <- simulate(change_list = c(20, 60, 100, 200, 300, 500), change_feature = "n", within_group = FALSE, group_size = 5, family = "binomial")



df1 <- bind_rows(within_p, within_n, without_p, without_n) %>% mutate(type = "linear")
df2 <- bind_rows(log_within_p, log_within_n, log_without_p, log_without_n) %>% mutate(type = "logistic")
df <- bind_rows(df1, df2)
saveRDS(df, "./running-time-records-current.rds")

```



